stages:
    - build
    - package
    - publish

build:
    stage: build
    image: maven:3.8.4-openjdk-17
    artifacts:
        paths:
            - target/chbc-livestream-macro-2.0.jar
    script: "mvn deploy -s $CI_PROJECT_DIR/settings.xml"

package:
    stage: package
    image: joshkeegan/zip:latest
    artifacts:
        paths:
            - chbc-livestream-macro.zip
    dependencies:
        - build
    script:
        - zip chbc-livestream-macro.zip target/chbc-livestream-macro-2.0.jar


publish:
    stage: publish
    image: curlimages/curl:latest
    dependencies:
        - package
    script:
        - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./chbc-livestream-macro.zip "https://gitlab.parkerthornton.net/api/v4/projects/3/packages/generic/chbc-livestream-macro/2.0.0/chbc-livestream-macro.zip?status=default"'