stages:
    - build
    - package
    - publish

variables:
    JARFILE: chbc-livestream-macro-2.0-jar-with-dependencies.jar
    ZIPPEDFILE: "chbc-livestream-macro-mac.zip"

build:
    stage: build
    image: maven:3.8.4-openjdk-17
    artifacts:
        paths:
            - target/*
    script: 
        - mvn clean
        - mvn package

package:
    stage: package
    image: ubuntu:latest
    artifacts:
        paths:
            - "$ZIPPEDFILE"
    dependencies:
        - build
    script:
        - apt install zip -y
        - mv target/$JARFILE "CHBC Livestream Macro.app/Contents/chbc-livestream-macro.jar"
        - zip -r $ZIPPEDFILE "CHBC Livestream Macro.app"


publish:
    stage: publish
    image: rancher/curlimages-curl:latest
    dependencies:
        - package
    script:
        - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./$ZIPPEDFILE "https://gitlab.parkerthornton.net/api/v4/projects/3/packages/generic/chbc-livestream-macro/2.0.0/$ZIPPEDFILE?status=default"'
