stages:
    - build
    - package
    - publish

variables:
    ZIPPEDFILE: "chbc-livestream-macro-build.zip"

build:
    stage: build
    image: maven:3.8.4-openjdk-17
    artifacts:
        paths:
            - target/chbc-livestream-macro-2.0.jar
    script: "mvn package"

package:
    stage: package
    image: joshkeegan/zip:latest
    artifacts:
        paths:
            - "$ZIPPEDFILE"
    dependencies:
        - build
    script:
        - mv target/chbc-livestream-macro-2.0.jar "CHBC Livestream Macro.app/Contents/chbc-livestream-macro.jar"
        - zip -r $ZIPPEDFILE "CHBC Livestream Macro.app"


publish:
    stage: publish
    image: curlimages/curl:latest
    dependencies:
        - package
    script:
        - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file ./$ZIPPEDFILE "https://gitlab.parkerthornton.net/api/v4/projects/3/packages/generic/chbc-livestream-macro/2.0.0/$ZIPPEDFILE?status=default"'